### ISSUE TITLE
Convert librestore/backend/bin/convert.py so it accepts 2 arguments instead of static value for input

### ISSUE THREAD

**Issue by sklei4** [spointfs/librestore#8]
Add argument instead of static value.

**Comment by yonMaor** [comment]
Hey, I'd like to help, but I'm new to open source. 
Any more details on this issue?

**Comment by sklei4** [comment]
Hi @yonMaor, thanks for looking into this.

Today the static values e.xlsx and Sheet1 in the convert.py script should be replaced with arguments.

So when I type `convery.py e.xlsx Sheet1` on my terminal, the result should be to process the arguments.

Here's a tutorial on Python arguments.

https://www.tutorialspoint.com/python3/python_command_line_arguments.htm

**Comment by yonMaor** [comment]
Hey @sklei4, I believe that I've solved the issue. 
Do I need to do any testing to make sure I haven't introduced new bugs?

**Comment by sklei4** [comment]
Send the PR, and I'll test it out. No automated tests available here yet because it's such a new project. Thanks for the effort.

**Comment by yonMaor** [comment]
Hey @sklei4. Done! Hope I haven't made any mistakes (still new to the process)

**Comment by sklei4** [comment]
Looks great. Thanks!
